seo: 
  site_name: Thai Street Paws Rescue
  title: Default SEO Title
  description: 
  keywords: 
  social_image: /images/logo.png
  author: 
  favicon_image: /images/favicon.png
social: 
  instagram_username: thaistreetpaws_dogrescue 
  facebook_url: https://www.facebook.com/thaistreetpawsrescue/
  twitter_username: 