seo: 
  site_name: Thai Street Paws Rescue
  title: Thai Street Paws Rescue
  description: Thai Street Paws Rescue is a non-profit organization, saving dogs from the streets of Thailand and setting them up for adoption in Europe and America.
  keywords: 
  social_image: /images/logo.png
  author: 
  favicon_image: /images/favicon.png
social: 
  instagram_username: thaistreetpaws_dogrescue 
  facebook_url: https://www.facebook.com/thaistreetpawsrescue/
  twitter_username: 